title: Ajaxinate - Shopify ajax pagination plugin
name: Ajaxinate
description: Shopify ajax pagination plugin
subtitle: Shopify ajax pagination plugin
github_url: https://github.com/Elkfox/Ajaxinate
download_url: https://github.com/Elkfox/Ajaxinate/archive/master.zip
demo_url: https://ajaxify.myshopify.com/collections/all
